Fixing error with keras missing legacy_get_updates_support
Building keras-contrib in a [jupyter/tensorflow-notebook](https://github.com/jupyter/docker-stacks) causes the error:

> AttributeError: module 'keras.legacy.interfaces' has no attribute 'legacy_get_updates_support'

This should fix that error.